# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Easy2Balla' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SVProgressHUD'
  # Pods for Easy2Balla

  target 'Easy2BallaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Easy2BallaUITests' do
    # Pods for testing
  end


end
